dataset:
  n_sample: 400
  train_ds:
    n_dataset: 51200

  valid_ds:
    n_dataset: 512

model:
  time_step: 300
  input_dim: 400
  hidden_dim: 96

trainer:
  epochs: 1000
  batch: 128
  seed: 1234
